# Generated by Django 3.2 on 2023-06-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filegoogle',
            name='google_id',
            field=models.CharField(max_length=40),
        ),
    ]
