# Generated by Django 3.2 on 2023-06-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_filegoogle_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetg',
            name='tg_id',
            field=models.CharField(max_length=100),
        ),
    ]
